config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
    resources :comments
  end

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :presence => true
  validates :text, :presence => true

  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :autho, except: [:show, :index]
  before_filter :authenticate_user!
  load_and_authorize_resource

  def create
    @post = Post.new(params.require(:post).permit(:title, :text))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.delete
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :text)
    end

    def autho
      authorize! if can? :update, @post
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= link_to 'Show', post %></td>
        <% if can? :edit, @post %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <%= @post.text %>
</p>

<%= link_to 'Show Comments Only', post_comments_path(@post) %> |
<%= link_to 'Post a Comment', new_post_comment_path(@post) %> |  |
<% if can? :edit, @post %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Destroy', @post, :confirm => 'Are you sure?', :method => :delete %> |  |
<% end %>
<%= link_to 'Back', posts_path %>


<p>
|| Comments ||
</p>>
<table>
  <tr>
    <th>....Author....|</th>
    <th>|....Comment....</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @post.comments.each do |comment| %>
    <tr>
      <td><%= comment.author %></td>
      <td><%= comment.text %></td>

      <td><%= link_to 'Show', post_comment_path(comment.post, comment) %></td>
      <% if can? :update, Post %>
        <td><%= link_to 'Edit', edit_post_comment_path(comment.post, comment)%></td>
        <td><%= link_to 'Delete', post_comment_path(comment.post, comment), :confirm => 'Are you sure?', :method => :delete %></td>
      <% end%>
    </tr>
<% end %>
</table>